.cmake/Modules/QtUtils.cmake
.gitignore
CMakeLists.txt
GUI/CMakeLists.txt
texthook/CMakeLists.txt
vnrhook/CMakeLists.txt

I don't really like to use QT itself and prefer to build it on one go through cmake.
The commit here adds cmake file for gui part and also automatically installs required DLLs through QT tool
Updated it to automatically find Qt for 2017 and 2015

Add cmake support for GUI part

---

include/text.h

Thanks for this tool! Since I don't have Visual Studio on my computer, I can't see how translation looks, if there are something wrong tell me.

Spanish translation

---

README.md
README_ES.md

It would be fine for final users.

Readme Spanish

---

README.md
README_SC.md
include/text.h

Haven't been tested since I don't have Qt, modify this commit if anything doesn't work.

Simplified Chinese translation & README

---

README.md
README_RU.md
text.cpp

Translated it on russian. Maybe later will be need some corrections after tests. 
Added RUSSIAN section to text.cpp, russian readme and link to it in original.
If some things is not need to translate then remove them. Check if all right.

Russian localization for GUI and Readme

---

README.md
README_ID.md
README_RU.md
deploy.ps1
text.cpp

Hi Artikash, 
I'm interested in contributing in your project so, i'm adding Indonesian language in your project

Added indonesian translation

---

text.cpp

Russian localization typos fix

---

text.cpp

Tried adding Portuguese_BR as a GUI language.

Adds Portuguese_BR

---

README.md
README_PT.md

Finishes up the Portuguese translation so far.

README_PT.md

---

README_PT.md
text.cpp

I noticed some Portuguese mistakes I made myself and reviewed a few terms to make it easier for people to read.

Portuguese translation edition

---

README_TH.md
text.cpp

Added readme.md in thai language as README_TH.md and added the text in text.cpp for the Thai language. 
I didn't compile and test it before but if the test is necessary, please reject the pull request and I will try to compile and test it before creating new pull request later.

added thai readme and text.cpp

---

text.cpp

Updated localization with new strings
p.s. Searching all new vars was too lazy for me and because I made [utility](https://github.com/TokcDK/Textractor-Localizations-Helper) for this which let update or add language much more faster.

Updated Russian localization

---

text.cpp

Updated text.cpp

---

extensions/googletranslate.cpp

Should stop crashes with 'out of range' error.

Fix google translate error handling

---

texthook/engine/engine.cc
texthook/util/util.cc
texthook/util/util.h

should fix system40 and rugp2 hooks

fix function finding (restore to ithvnr)

---

deploy.ps1
extensions/CMakeLists.txt
extensions/devtoolssystrantranslate.cpp

DevTools Systran Translate.
Automatic consent of cookies for translators via web page.

DevTools Systran Translate

---

deploy.ps1
extensions/CMakeLists.txt
extensions/devtoolspapagotranslate.cpp

DevTools Papago Translate
First release

DevTools Papago Translate

---

extensions/deepltranslate.cpp

Added Turkish and Indonesian languages selection

DeepL Translate: Added Turkish and Indonesian

---

README_ID.md

Fix some Indonesian translations that still english to make it little bit formal in Indonesian, but still understandable for young people.

[ID] Removing some English words and fix translations

---

texthook/engine/engine.cc

Added dynamic reader hook to GetTextExtentPoint32A function
Tested with VN v17900 "Chuuni Hime no Teikoku"

update ShinaRio 2.50+
